## *Fashion MNIST* konvoliucinis neuroninis tinklas

### Bibliotekų improtavimas

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import datasets, layers, models, activations
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import copy
import os
import random

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
def create_dir(path):
  if not os.path.exists(path):
    os.makedirs(path)

# dir for all exports
create_dir("/content/drive/MyDrive/conv")

def prefix_dir(title_ext):
  return "/content/drive/MyDrive/conv/" + title_ext

In [ ]:
# TODO: write best model save, count from best value

In [ ]:
# make the experiment as deterministic as possible
tf.reset_default_graph()
tf.random.set_seed(0)
random.seed(0)
np.random.seed(0)

### *Fashion MNIST* klasės

In [ ]:
classes = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]
classes = pd.DataFrame(
          columns=["Class", "Index"],
          data=zip(classes, range(len(classes))))
classes

         Class  Index
0  T-shirt/top      0
1      Trouser      1
2     Pullover      2
3        Dress      3
4         Coat      4
5       Sandal      5
6        Shirt      6
7      Sneaker      7
8          Bag      8
9   Ankle boot      9

In [ ]:
classes.to_latex(prefix_dir("classes.tex"), index=False)

###Eksperimento parametrų generavimas

In [ ]:
# options to randomly pick from for finding the best parameters
available_params = {
    "Activation function" : ["sigmoid", "tanh", "softmax"],
    "Epoch count" : [10, 30, 50, 70],
    "Learning rate" : [0.01, 0.02, 0.03, 0.04],
    "Batch size" : [32, 64, 128, 256],
    "Kernel size" : [3, 4, 5, 6],
    "Pool size" : [2, 3, 5, 6],
    "Filter count" : [28, 86, 128, 256],
    "Dropout rate" : [0.2, 0.4, 0.5, 0.6],
    "Optimizer" : ["adam", "rmsprop", "adagrad", "sgd"],
    "Architecture": ["full", "no batch norm", "no dropout"]
}

# available_params = {
#     "Activation function" : ["sigmoid", "tanh", "softmax"],
#     "Epoch count" : [10, 30],
#     "Learning rate" : [0.01, 0.02],
#     "Batch size" : [32, 64],
#     "Kernel size" : [3, 4],
#     "Pool size" : [2, 3],
#     "Filter count" : [48, 96],
#     "Dropout rate" : [0.2, 0.4],
#     "Optimizer" : ["adam", "rmsprop"],
#     "Architecture": ["full", "no batch norm"]
# }

# available_params = {
#     "Activation function" : ["sigmoid", "tanh", "softmax"],
#     "Epoch count" : [10],
#     "Learning rate" : [0.01],
#     "Batch size" : [32],
#     "Kernel size" : [3],
#     "Pool size" : [2],
#     "Filter count" : [48],
#     "Dropout rate" : [0.2],
#     "Optimizer" : ["adam"],
#     "Architecture": ["full"]
# }

# sort values
for column in available_params.keys():
  available_params[column] = sorted(available_params[column])

def get_first_params(available_params):
  rand_params = {}
  for column, available in available_params.items():
    rand_params[column] = [available[0]]
  return rand_params

In [ ]:
# set base for experiment
rand_params_base = pd.DataFrame(get_first_params(available_params))

# the params that will be generated from base
params = pd.DataFrame(columns=available_params.keys())

# make a copy of available params because it will be modified
available_params_copy = copy.deepcopy(available_params)

# remove used values from available params copy
for column in rand_params_base.columns:
  available_params_copy[column].remove(rand_params_base.loc[0, column])

# apply available params for every column on base case to params
for column, available in available_params_copy.items():
  while len(available) > 0:
    append_index = params.shape[0]
    # copy last to new row
    params.loc[append_index] = rand_params_base.loc[0]
    # print(params.loc[append_index])
    random_available = available[0]#np.random.choice(available)
    params.loc[append_index, column] = random_available
    available.remove(random_available)

# params
def sort_columns_by_range(available_params, params):
  # available_params_iter = iter(available_params.keys())
  # # ignore first column
  # # don't sort base case
  # column = next(available_params_iter)
  # # [[0]] - returns DataFrame instead of Series
  sorted_series = []
  # sorted_series = [
  #     params.iloc[[0]],
  #     params.iloc[1:len(available_params[column])-1].sort_values(by=column)
  # ]
  # print(sorted_series[0])
  # print(sorted_series[1])
  i = 0
  for column in available_params.keys():
    next_i = i + len(available_params[column])-1
    # print(params.iloc[i:next_i])
    # print(params.iloc[i:next_i].sort_values(by=column))
    # return
    sorted_series.append(params.iloc[i:next_i].sort_values(by=column))
    i = next_i
  return pd.concat(sorted_series)

params = sort_columns_by_range(available_params, params)

# append base case to generated params
params.loc[params.shape[0]] = rand_params_base.loc[0]
params

,Activation function,Epoch count,Learning rate,Batch size,Kernel size,Pool size,Filter count,Dropout rate,Optimizer,Architecture
0,softmax,10,0.01,32,3,2,28,0.2,adagrad,full
1,tanh,10,0.01,32,3,2,28,0.2,adagrad,full
2,sigmoid,30,0.01,32,3,2,28,0.2,adagrad,full
3,sigmoid,50,0.01,32,3,2,28,0.2,adagrad,full
4,sigmoid,70,0.01,32,3,2,28,0.2,adagrad,full
5,sigmoid,10,0.02,32,3,2,28,0.2,adagrad,full
6,sigmoid,10,0.03,32,3,2,28,0.2,adagrad,full
7,sigmoid,10,0.04,32,3,2,28,0.2,adagrad,full
8,sigmoid,10,0.01,64,3,2,28,0.2,adagrad,full
9,sigmoid,10,0.01,128,3,2,28,0.2,adagrad,full
10,sigmoid,10,0.01,256,3,2,28,0.2,adagrad,full
11,sigmoid,10,0.01,32,4,2,28,0.2,adagrad,full
12,sigmoid,10,0.01,32,5,2,28,0.2,adagrad,full
13,sigmoid,10,0.01,32,6,2,28,0.2,adagrad,full
14,sigmoid,10,0.01,32,3,3,28,0.2,adagrad,full
15,sigmoid,10,0.01,32,3,5,28,0.2,adagrad,full
16,sigmoid,10,0.01,32,3,6,28,0.2,adagrad,full
17,sigmoid,10,0.01,32,3,2,86,0.2,adagrad,full
18,sigmoid,10,0.01,32,3,2,128,0.2,adagrad,full
19,sigmoid,10,0.01,32,3,2,256,0.2,adagrad,full
20,sigmoid,10,0.01,32,3,2,28,0.4,adagrad,full
21,sigmoid,10,0.01,32,3,2,28,0.5,adagrad,full
22,sigmoid,10,0.01,32,3,2,28,0.6,adagrad,full
23,sigmoid,10,0.01,32,3,2,28,0.2,adam,full
24,sigmoid,10,0.01,32,3,2,28,0.2,rmsprop,full
25,sigmoid,10,0.01,32,3,2,28,0.2,sgd,full
26,sigmoid,10,0.01,32,3,2,28,0.2,adagrad,no batch norm
27,sigmoid,10,0.01,32,3,2,28,0.2,adagrad,no dropout
28,sigmoid,10,0.01,32,3,2,28,0.2,adagrad,full

### Papildomos funkcijos palengvinimui

In [ ]:
# do the same func operation inside list elements as if it was a flattened list
mapin = lambda func: lambda lst: type(lst)(map(lambda x:
    func(x) if not isinstance(x, (list, tuple)) else mapin(func)(x), lst))

### Atsisiunčiami *Fashion MNIST* duomenys

In [ ]:
fashion_mnist = datasets.fashion_mnist.load_data()

### Tikrinama duomenų struktūrą

In [ ]:
(x_train, y_train), (x_test, y_test) = fashion_mnist
mapin(lambda x: x.shape)(fashion_mnist)

(((60000, 28, 28), (60000,)), ((10000, 28, 28), (10000,)))

### Pavaizduojami antros ir ketvirtos duomenų eilutės paveikslėliai bei tikrosios klasės indeksai

In [ ]:
print(x_train.__class__)
display(x_train[1], x_train[3])
print("klases: ", y_train[1], y_train[3])

<class 'numpy.ndarray'>

array([[  0,   0,   0,   0,   0,   1,   0,   0,   0,   0,  41, 188, 103,
         54,  48,  43,  87, 168, 133,  16,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   1,   0,   0,   0,  49, 136, 219, 216, 228, 236,
        255, 255, 255, 255, 217, 215, 254, 231, 160,  45,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,  14, 176, 222, 224, 212, 203, 198, 196,
        200, 215, 204, 202, 201, 201, 201, 209, 218, 224, 164,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0, 188, 219, 200, 198, 202, 198, 199, 199,
        201, 196, 198, 198, 200, 200, 200, 200, 201, 200, 225,  41,   0,
          0,   0],
       [  0,   0,   0,   0,  51, 219, 199, 203, 203, 212, 238, 248, 250,
        245, 249, 246, 247, 252, 248, 235, 207, 203, 203, 222, 140,   0,
          0,   0],
       [  0,   0,   0,   0, 116, 226, 206, 204, 207, 204, 101,  75,  47,
         73,  48,  50,  45,  51,  63, 113, 222, 202, 206, 220, 224,   0,
          0,   0],
       [  0,   0,   0,   0, 200, 222, 209, 203, 215, 200,   0,  70,  98,
          0, 103,  59,  68,  71,  49,   0, 219, 206, 214, 210, 250,  38,
          0,   0],
       [  0,   0,   0,   0, 247, 218, 212, 210, 215, 214,   0, 254, 243,
        139, 255, 174, 251, 255, 205,   0, 215, 217, 214, 208, 220,  95,
          0,   0],
       [  0,   0,   0,  45, 226, 214, 214, 215, 224, 205,   0,  42,  35,
         60,  16,  17,  12,  13,  70,   0, 189, 216, 212, 206, 212, 156,
          0,   0],
       [  0,   0,   0, 164, 235, 214, 211, 220, 216, 201,  52,  71,  89,
         94,  83,  78,  70,  76,  92,  87, 206, 207, 222, 213, 219, 208,
          0,   0],
       [  0,   0,   0, 106, 187, 223, 237, 248, 211, 198, 252, 250, 248,
        245, 248, 252, 253, 250, 252, 239, 201, 212, 225, 215, 193, 113,
          0,   0],
       [  0,   0,   0,   0,   0,  17,  54, 159, 222, 193, 208, 192, 197,
        200, 200, 200, 200, 201, 203, 195, 210, 165,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  47, 225, 192, 214, 203, 206,
        204, 204, 205, 206, 204, 212, 197, 218, 107,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   1,   6,   0,  46, 212, 195, 212, 202, 206,
        205, 204, 205, 206, 204, 212, 200, 218,  91,   0,   3,   1,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,  11, 197, 199, 205, 202, 205,
        206, 204, 205, 207, 204, 205, 205, 218,  77,   0,   5,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   3,   0,   2, 191, 198, 201, 205, 206,
        205, 205, 206, 209, 206, 199, 209, 219,  74,   0,   5,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   2,   0,   0, 188, 197, 200, 207, 207,
        204, 207, 207, 210, 208, 198, 207, 221,  72,   0,   4,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   2,   0,   0, 215, 198, 203, 206, 208,
        205, 207, 207, 210, 208, 200, 202, 222,  75,   0,   4,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 212, 198, 209, 206, 209,
        206, 208, 207, 211, 206, 205, 198, 221,  80,   0,   3,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 204, 201, 205, 208, 207,
        205, 211, 205, 210, 210, 209, 195, 221,  96,   0,   3,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 202, 201, 205, 209, 207,
        205, 213, 206, 210, 209, 210, 194, 217, 105,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 204, 204, 205, 208, 207,
        205, 215, 207, 210, 208, 211, 193, 213, 115,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 204, 207, 207, 208, 206,
        206, 215, 210, 210, 207, 212, 195, 210, 118,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 198, 208, 208, 208, 204,
        207, 212, 212, 210, 207, 211, 196, 207, 121,   0,   1,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 198, 210, 207, 208, 206,
        209, 213, 212, 211, 207, 210, 197, 207, 124,   0,   1,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 172, 210, 203, 201, 199,
        204, 207, 205, 204, 201, 205, 197, 206, 127,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 188, 221, 214, 234, 236,
        238, 244, 244, 244, 240, 243, 214, 224, 162,   0,   2,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0, 139, 146, 130, 135, 135,
        137, 125, 124, 125, 121, 119, 114, 130,  76,   0,   0,   0,   0,
          0,   0]], dtype=uint8)

array([[  0,   0,   0,   0,   0,   0,   0,   0,  33,  96, 175, 156,  64,
         14,  54, 137, 204, 194, 102,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  73, 186, 177, 183, 175, 188, 232,
        255, 223, 219, 194, 179, 186, 213, 146,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,  35, 163, 140, 150, 152, 150, 146, 175,
        175, 173, 171, 156, 152, 148, 129, 156, 140,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0, 150, 142, 140, 152, 160, 156, 146, 142,
        127, 135, 133, 140, 140, 137, 133, 125, 169,  75,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,  54, 167, 146, 129, 142, 137, 137, 131,
        148, 148, 133, 131, 131, 131, 125, 140, 140,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 110, 188, 133, 146, 152, 133, 125,
        127, 119, 129, 133, 119, 140, 131, 150,  14,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 221, 158, 137, 135, 123, 110,
        110, 114, 108, 112, 117, 127, 142,  77,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   4,   0,  25, 158, 137, 125, 119, 119,
        110, 117, 117, 110, 119, 127, 144,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 123, 156, 129, 112, 110,
        102, 112, 100, 121, 117, 129, 114,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 125, 169, 127, 119, 106,
        108, 104,  94, 121, 114, 129,  91,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  98, 171, 129, 112, 104,
        114, 106, 102, 112, 104, 133,  64,   0,   4,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  66, 173, 135, 129,  98,
        100, 119, 102, 108,  98, 135,  60,   0,   4,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  56, 171, 135, 127, 100,
        108, 117,  85, 106, 110, 135,  66,   0,   4,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  52, 150, 129, 110, 100,
         91, 102,  94,  83, 104, 123,  66,   0,   4,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   2,   0,  66, 167, 140, 148, 148,
        127, 137, 152, 146, 146, 148,  96,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  45, 123,  94, 104,  96,
        119, 121, 106,  98, 112,  87, 114,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 106,  89,  58,  50,  37,
         50,  66,  56,  50,  75,  75, 137,  22,   0,   2,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   2,   0,  29, 148, 114, 106, 125,  89,
        100, 133, 117, 131, 131, 131, 125, 112,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 100, 106, 114,  91, 137,  62,
        102, 131,  89, 135, 112, 131, 108, 135,  37,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 146, 100, 108,  98, 144,  62,
        106, 131,  87, 133, 104, 160, 117, 121,  68,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  33, 121, 108,  96, 100, 140,  71,
        106, 127,  85, 140, 104, 150, 140, 114,  89,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  62, 119, 112, 102, 110, 137,  75,
        106, 144,  81, 144, 108, 117, 154, 117, 104,  18,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  66, 121, 102, 112, 117, 131,  73,
        104, 156,  77, 137, 135,  83, 179, 129, 121,  35,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 127,  81, 125, 133, 119,  79,
        100, 169,  83, 129, 175,  60, 163, 135, 146,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 106, 129,  62, 140, 144, 108,  85,
         83, 158,  85, 129, 175,  48, 146, 133, 135,  64,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 117, 119,  79, 140, 152, 102,  89,
        110, 137,  96, 150, 196,  83, 144, 135, 133,  77,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 154, 121,  87, 140, 154, 112,  94,
         52, 142, 100,  83, 152,  85, 160, 133, 100,  12,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   4,   0,   2,   0,  35,   4,  33,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=uint8)

klases:  0 3

###Normalizuojamos pikselių reikšmes, kad jos nebūtų didelės

In [ ]:
# normalize pixel value range [0, 255] -> [0, 1]
normalized_mnist_dataset = mapin(lambda x: x/255)(fashion_mnist)

###Testavimo ir validavimo perskirstymai sujungiami atgal į aibes

In [ ]:
x = np.concatenate((x_train, x_test))
y = np.concatenate((y_train, y_test))

In [ ]:
x.shape, y.shape

((70000, 28, 28), (70000,))

###Duomenys perskirstomi pagal naują funkciją į testavimo, validavimo ir treniravimo aibes

In [ ]:
def split(x, y, train_percent, valid_percent):
  train_size = int(x.shape[0] * train_percent)
  valid_size = int(x.shape[0] * valid_percent)
  train_slice = slice(0, train_size)
  valid_slice = slice(train_size, train_size + valid_size)
  test_slice = slice(train_size + valid_size, x.shape[0])
  x_train = x[train_slice]
  x_valid = x[valid_slice]
  x_test = x[test_slice]
  y_train = y[train_slice]
  y_valid = y[valid_slice]
  y_test = y[test_slice]
  return (x_train, x_valid, x_test), (y_train, y_valid, y_test)

split_vals = split(x, y, train_percent = 0.8, valid_percent = 0.1)
print(mapin(lambda x: x.shape)(split_vals))
(x_train, x_valid, x_test), (y_train, y_valid, y_test) = split_vals

(((56000, 28, 28), (7000, 28, 28), (7000, 28, 28)), ((56000,), (7000,), (7000,)))

In [ ]:
x_train.__class__

numpy.ndarray

###Sukuriamas neuroninis tinklas

In [ ]:
# https://www.tensorflow.org/tutorials/images/cnn

class ConvNet():
  def __init__(self, architecture_name, activation, dropout_rate, pool_size, kernel_size, filter_count):
    self.architect(architecture_name, dropout_rate, pool_size, kernel_size, filter_count)

  def architect(self, architecture_name, activation, dropout_rate, pool_size, kernel_size, filter_count):
    model = models.Sequential()
    model.add(layers.Conv2D(filter_count, (kernel_size, kernel_size), activation='relu', input_shape=(28, 28, 1)))
    model.add(layers.MaxPooling2D((pool_size, pool_size)))
    model.add(layers.Dropout(dropout_rate)) if architecture_name != 'no dropout' else None
    model.add(layers.BatchNormalization()) if architecture_name != 'no batch norm' else None
    model.add(layers.Conv2D(2*filter_count, (kernel_size, kernel_size), activation='relu'))
    model.add(layers.MaxPooling2D((pool_size, pool_size)))
    model.add(layers.Dropout(dropout_rate)) if architecture_name != 'no dropout' else None
    model.add(layers.BatchNormalization()) if architecture_name != 'no batch norm' else None
    model.add(layers.Conv2D(2*filter_count, (kernel_size, kernel_size), activation='relu'))
    model.add(layers.BatchNormalization()) if architecture_name != 'no batch norm' else None
    model.add(layers.Flatten())
    model.add(layers.Dense(56, activation='relu'))
    model.add(layers.BatchNormalization()) if architecture_name != 'no batch norm' else None
    model.add(layers.Dense(10, activation=activation))
    self.model = model

  def compile(self, optimizer, metrics=['accuracy']):
    self.model.compile(
        optimizer=optimizer,
        loss=tf.keras.losses.SparseCategoricalCrossentropy(),
        metrics=metrics)

  def train(self, x, y, x_valid, y_valid, batch_size, epochs):
    return self.model.fit(
        x, y, epochs=epochs,
        validation_data=(x_valid, y_valid),
        batch_size=batch_size
      )

  def evaluate(self, x, y, callbacks):
    loss, accuracy = self.model.evaluate(x, y, callbacks=callbacks, verbose=2)
    return loss, accuracy * 100

  def get_predictions(self, x):
    return self.model.predict(x)

  def summarize(self):
    self.model.summary()

In [ ]:
a = np.arange(10, 50, 5)
print(a)
b = np.arange(20, 60, 5)
b = np.append(b, 25)
print(b)
c = [3]
c.extend(np.arange(10))
c.extend(np.arange(10))
print(c)

[10 15 20 25 30 35 40 45]
[20 25 30 35 40 45 50 55 25]
[3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

###Modelių sudarymo ciklas su skirtingais parametrais

In [ ]:
import pandas as pd

data = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30],
  "qualified": [True, False, False]
}

df = pd.DataFrame(data)

newdf = df.drop(1, axis='index')

print(newdf)

    name  age  qualified
0  Sally   50       True
2   John   30      False

In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 28, 35]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
df.drop(df.iloc[2].name)

    Name  Age
a  Alice   25
b    Bob   30
d  David   35

In [ ]:
a = [1,2,3]
a.remove(3)
a

[1, 2]

In [ ]:
# https://colab.research.google.com/notebooks/gpu.ipynb#scrollTo=sXnDmXR7RDr2

results = {"Loss": [], "Accuracy": []}
# dummy learning rate initialization for updating in the loop
# https://medium.com/@danielonugha0/how-to-change-the-learning-rate-of-tensorflow-b5d854819050
learning_rate = tf.Variable(0.01, trainable=False)
max_accuracy, min_loss = 0, np.inf
best_predictions = None
LOSS_BASELINE = 0.2
ACCURACY_BASELINE = 80
device = '/device:GPU:0' if tf.test.gpu_device_name() == '/device:GPU:0' else '/cpu:0'

for i in range(len(params)):
  print(f"\nPARAM_SET: {i}")
  row = params.iloc[i]
  print(row)
  try:
    model = ConvNet(row.loc["Architecture"], row.loc["Activation"], row.loc["Dropout rate"], row.loc["Pool size"], row.loc["Kernel size"], row.loc["Filter count"])
    model.summarize()
    model_checkpoint_callback = keras.callbacks.ModelCheckpoint(
      filepath=prefix_dir("saved_best_acc.model.keras"),
      monitor='accuracy',
      mode='max',
      save_best_only=True)
    model.compile(row.loc["Optimizer"])
    tf.keras.backend.set_value(learning_rate, row.loc["Learning rate"])
    # x_test = np.array(x_test)
    # x_valid = np.array(x_valid)
    x_full_test = np.concatenate((x_valid, x_test))
    y_full_test = np.concatenate((y_valid, y_test))
    with tf.device(device):
      history = model.train(x_train, y_train, x_valid, y_valid, row.loc["Batch size"], row.loc["Epoch count"])
      loss, accuracy = model.evaluate(x_full_test, y_full_test, callbacks=[model_checkpoint_callback])
      loss = round((loss - LOSS_BASELINE) / LOSS_BASELINE * 100, 2)
      accuracy = round((accuracy - ACCURACY_BASELINE) / ACCURACY_BASELINE * 100, 2)
      if accuracy > max_accuracy:
        max_accuracy = accuracy
        min_loss = loss
        best_predictions = model.get_predictions(x_full_test)
    results["Loss"].append(loss)
    results["Accuracy"].append(accuracy)
    print(f"\nLoss: {loss:.2f}%, Accuracy: {accuracy:.2f}%\n")
  except:
    print("\n\n-------------Exception occurred, continuing...-------------\n\n")
    # remove these params from experiment
    params = params.drop(params.iloc[i].name)
    for column, value in available_params.items():
      available_params[column].remove(value)
    continue

PARAMS_LOSS_NAME = f"Loss percent change from baseline {LOSS_BASELINE}"
PARAMS_ACC_NAME = f"Accuracy percent change from baseline {ACCURACY_BASELINE}%"

params["Loss"] = results["Loss"]
params["Accuracy"] = results["Accuracy"]

PARAM_SET: 0
Activation function    softmax
Epoch count                 10
Learning rate             0.01
Batch size                  32
Kernel size                  3
Pool size                    2
Filter count                28
Dropout rate               0.2
Optimizer              adagrad
Architecture              full
Name: 0, dtype: object
Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_9 (Conv2D)           (None, 26, 26, 28)        280

 max_pooling2d_6 (MaxPoolin  (None, 13, 13, 28)        0
 g2D)

 dropout_6 (Dropout)         (None, 13, 13, 28)        0

 batch_normalization_12 (Ba  (None, 13, 13, 28)        112
 tchNormalization)

 conv2d_10 (Conv2D)          (None, 11, 11, 56)        14168

 max_pooling2d_7 (MaxPoolin  (None, 5, 5, 56)          0
 g2D)

 dropout_7 (Dropout)         (None, 5, 5, 56)          0

 batch_normalization_13 (Ba  (None, 5, 5, 56)          224
 tchNormalization)

 conv2d_11 (Conv2D)          (None, 3, 3, 56)          28280

 batch_normalization_14 (Ba  (None, 3, 3, 56)          224
 tchNormalization)

 flatten_3 (Flatten)         (None, 504)               0

 dense_6 (Dense)             (None, 56)                28280

 batch_normalization_15 (Ba  (None, 56)                224
 tchNormalization)

 dense_7 (Dense)             (None, 10)                570

=================================================================
Total params: 72362 (282.66 KB)
Trainable params: 71970 (281.13 KB)
Non-trainable params: 392 (1.53 KB)
_________________________________________________________________
Epoch 1/10
1750/1750 [==============================] - 13s 6ms/step - loss: 0.9296 - accuracy: 0.6827 - val_loss: 0.6168 - val_accuracy: 0.7784
Epoch 2/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6833 - accuracy: 0.7599 - val_loss: 0.5561 - val_accuracy: 0.7970
Epoch 3/10
1750/1750 [==============================] - 11s 6ms/step - loss: 0.6221 - accuracy: 0.7792 - val_loss: 0.5228 - val_accuracy: 0.8099
Epoch 4/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5878 - accuracy: 0.7909 - val_loss: 0.4995 - val_accuracy: 0.8174
Epoch 5/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5683 - accuracy: 0.7990 - val_loss: 0.4787 - val_accuracy: 0.8227
Epoch 6/10
1750/1750 [==============================] - 9s 5ms/step - loss: 0.5470 - accuracy: 0.8063 - val_loss: 0.4681 - val_accuracy: 0.8260
Epoch 7/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5308 - accuracy: 0.8099 - val_loss: 0.4569 - val_accuracy: 0.8281
Epoch 8/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5202 - accuracy: 0.8139 - val_loss: 0.4473 - val_accuracy: 0.8314
Epoch 9/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5087 - accuracy: 0.8188 - val_loss: 0.4394 - val_accuracy: 0.8333
Epoch 10/10
1750/1750 [==============================] - 10s 5ms/step - loss: 0.4996 - accuracy: 0.8207 - val_loss: 0.4318 - val_accuracy: 0.8363
438/438 - 1s - loss: 0.4420 - accuracy: 0.8361 - 1s/epoch - 2ms/step
438/438 [==============================] - 1s 2ms/step

Loss: 120.98%, Accuracy: 4.52%


PARAM_SET: 1
Activation function       tanh
Epoch count                 10
Learning rate             0.01
Batch size                  32
Kernel size                  3
Pool size                    2
Filter count                28
Dropout rate               0.2
Optimizer              adagrad
Architecture              full
Name: 1, dtype: object
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_12 (Conv2D)          (None, 26, 26, 28)        280

 max_pooling2d_8 (MaxPoolin  (None, 13, 13, 28)        0
 g2D)

 dropout_8 (Dropout)         (None, 13, 13, 28)        0

 batch_normalization_16 (Ba  (None, 13, 13, 28)        112
 tchNormalization)

 conv2d_13 (Conv2D)          (None, 11, 11, 56)        14168

 max_pooling2d_9 (MaxPoolin  (None, 5, 5, 56)          0
 g2D)

 dropout_9 (Dropout)         (None, 5, 5, 56)          0

 batch_normalization_17 (Ba  (None, 5, 5, 56)          224
 tchNormalization)

 conv2d_14 (Conv2D)          (None, 3, 3, 56)          28280

 batch_normalization_18 (Ba  (None, 3, 3, 56)          224
 tchNormalization)

 flatten_4 (Flatten)         (None, 504)               0

 dense_8 (Dense)             (None, 56)                28280

 batch_normalization_19 (Ba  (None, 56)                224
 tchNormalization)

 dense_9 (Dense)             (None, 10)                570

=================================================================
Total params: 72362 (282.66 KB)
Trainable params: 71970 (281.13 KB)
Non-trainable params: 392 (1.53 KB)
_________________________________________________________________
Epoch 1/10
1750/1750 [==============================] - 12s 6ms/step - loss: 0.9493 - accuracy: 0.6662 - val_loss: 0.6307 - val_accuracy: 0.7661
Epoch 2/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6844 - accuracy: 0.7532 - val_loss: 0.5632 - val_accuracy: 0.7876
Epoch 3/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6293 - accuracy: 0.7706 - val_loss: 0.5294 - val_accuracy: 0.8021
Epoch 4/10
1750/1750 [==============================] - 9s 5ms/step - loss: 0.5951 - accuracy: 0.7828 - val_loss: 0.5063 - val_accuracy: 0.8106
Epoch 5/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5701 - accuracy: 0.7908 - val_loss: 0.4883 - val_accuracy: 0.8186
Epoch 6/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5507 - accuracy: 0.7994 - val_loss: 0.4735 - val_accuracy: 0.8271
Epoch 7/10
1750/1750 [==============================] - 9s 5ms/step - loss: 0.5378 - accuracy: 0.8051 - val_loss: 0.4616 - val_accuracy: 0.8301
Epoch 8/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5249 - accuracy: 0.8106 - val_loss: 0.4516 - val_accuracy: 0.8349
Epoch 9/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5139 - accuracy: 0.8138 - val_loss: 0.4424 - val_accuracy: 0.8371
Epoch 10/10
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5040 - accuracy: 0.8181 - val_loss: 0.4349 - val_accuracy: 0.8400
438/438 - 1s - loss: 0.4465 - accuracy: 0.8359 - 942ms/epoch - 2ms/step

Loss: 123.26%, Accuracy: 4.49%


PARAM_SET: 2
Activation function    sigmoid
Epoch count                 30
Learning rate             0.01
Batch size                  32
Kernel size                  3
Pool size                    2
Filter count                28
Dropout rate               0.2
Optimizer              adagrad
Architecture              full
Name: 2, dtype: object
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_15 (Conv2D)          (None, 26, 26, 28)        280

 max_pooling2d_10 (MaxPooli  (None, 13, 13, 28)        0
 ng2D)

 dropout_10 (Dropout)        (None, 13, 13, 28)        0

 batch_normalization_20 (Ba  (None, 13, 13, 28)        112
 tchNormalization)

 conv2d_16 (Conv2D)          (None, 11, 11, 56)        14168

 max_pooling2d_11 (MaxPooli  (None, 5, 5, 56)          0
 ng2D)

 dropout_11 (Dropout)        (None, 5, 5, 56)          0

 batch_normalization_21 (Ba  (None, 5, 5, 56)          224
 tchNormalization)

 conv2d_17 (Conv2D)          (None, 3, 3, 56)          28280

 batch_normalization_22 (Ba  (None, 3, 3, 56)          224
 tchNormalization)

 flatten_5 (Flatten)         (None, 504)               0

 dense_10 (Dense)            (None, 56)                28280

 batch_normalization_23 (Ba  (None, 56)                224
 tchNormalization)

 dense_11 (Dense)            (None, 10)                570

=================================================================
Total params: 72362 (282.66 KB)
Trainable params: 71970 (281.13 KB)
Non-trainable params: 392 (1.53 KB)
_________________________________________________________________
Epoch 1/30
1750/1750 [==============================] - 12s 6ms/step - loss: 0.9673 - accuracy: 0.6705 - val_loss: 0.6318 - val_accuracy: 0.7703
Epoch 2/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6878 - accuracy: 0.7565 - val_loss: 0.5582 - val_accuracy: 0.8009
Epoch 3/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6264 - accuracy: 0.7775 - val_loss: 0.5202 - val_accuracy: 0.8150
Epoch 4/30
1750/1750 [==============================] - 11s 6ms/step - loss: 0.5894 - accuracy: 0.7908 - val_loss: 0.4963 - val_accuracy: 0.8201
Epoch 5/30
1750/1750 [==============================] - 11s 6ms/step - loss: 0.5654 - accuracy: 0.7998 - val_loss: 0.4752 - val_accuracy: 0.8264
Epoch 6/30
1750/1750 [==============================] - 11s 6ms/step - loss: 0.5435 - accuracy: 0.8054 - val_loss: 0.4638 - val_accuracy: 0.8306
Epoch 7/30
1750/1750 [==============================] - 9s 5ms/step - loss: 0.5275 - accuracy: 0.8131 - val_loss: 0.4488 - val_accuracy: 0.8366
Epoch 8/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5178 - accuracy: 0.8156 - val_loss: 0.4389 - val_accuracy: 0.8397
Epoch 9/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5040 - accuracy: 0.8200 - val_loss: 0.4304 - val_accuracy: 0.8449
Epoch 10/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4953 - accuracy: 0.8232 - val_loss: 0.4245 - val_accuracy: 0.8463
Epoch 11/30
1750/1750 [==============================] - 10s 5ms/step - loss: 0.4841 - accuracy: 0.8287 - val_loss: 0.4156 - val_accuracy: 0.8501
Epoch 12/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4794 - accuracy: 0.8292 - val_loss: 0.4101 - val_accuracy: 0.8514
Epoch 13/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4731 - accuracy: 0.8319 - val_loss: 0.4041 - val_accuracy: 0.8533
Epoch 14/30
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4668 - accuracy: 0.8332 - val_loss: 0.3987 - val_accuracy: 0.8546
Epoch 15/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4622 - accuracy: 0.8356 - val_loss: 0.3953 - val_accuracy: 0.8553
Epoch 16/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4561 - accuracy: 0.8382 - val_loss: 0.3913 - val_accuracy: 0.8574
Epoch 17/30
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4524 - accuracy: 0.8394 - val_loss: 0.3848 - val_accuracy: 0.8589
Epoch 18/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4449 - accuracy: 0.8418 - val_loss: 0.3821 - val_accuracy: 0.8607
Epoch 19/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4463 - accuracy: 0.8412 - val_loss: 0.3796 - val_accuracy: 0.8614
Epoch 20/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4365 - accuracy: 0.8454 - val_loss: 0.3768 - val_accuracy: 0.8614
Epoch 21/30
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4339 - accuracy: 0.8442 - val_loss: 0.3726 - val_accuracy: 0.8633
Epoch 22/30
1750/1750 [==============================] - 11s 6ms/step - loss: 0.4331 - accuracy: 0.8450 - val_loss: 0.3692 - val_accuracy: 0.8656
Epoch 23/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4283 - accuracy: 0.8461 - val_loss: 0.3675 - val_accuracy: 0.8650
Epoch 24/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4245 - accuracy: 0.8491 - val_loss: 0.3657 - val_accuracy: 0.8661
Epoch 25/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4229 - accuracy: 0.8493 - val_loss: 0.3637 - val_accuracy: 0.8657
Epoch 26/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4197 - accuracy: 0.8500 - val_loss: 0.3599 - val_accuracy: 0.8673
Epoch 27/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4196 - accuracy: 0.8501 - val_loss: 0.3591 - val_accuracy: 0.8670
Epoch 28/30
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4152 - accuracy: 0.8517 - val_loss: 0.3561 - val_accuracy: 0.8673
Epoch 29/30
1750/1750 [==============================] - 12s 7ms/step - loss: 0.4125 - accuracy: 0.8521 - val_loss: 0.3542 - val_accuracy: 0.8684
Epoch 30/30
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4080 - accuracy: 0.8536 - val_loss: 0.3529 - val_accuracy: 0.8704
438/438 - 1s - loss: 0.3652 - accuracy: 0.8661 - 928ms/epoch - 2ms/step
438/438 [==============================] - 1s 2ms/step

Loss: 82.59%, Accuracy: 8.26%


PARAM_SET: 3
Activation function    sigmoid
Epoch count                 50
Learning rate             0.01
Batch size                  32
Kernel size                  3
Pool size                    2
Filter count                28
Dropout rate               0.2
Optimizer              adagrad
Architecture              full
Name: 3, dtype: object
Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_18 (Conv2D)          (None, 26, 26, 28)        280

 max_pooling2d_12 (MaxPooli  (None, 13, 13, 28)        0
 ng2D)

 dropout_12 (Dropout)        (None, 13, 13, 28)        0

 batch_normalization_24 (Ba  (None, 13, 13, 28)        112
 tchNormalization)

 conv2d_19 (Conv2D)          (None, 11, 11, 56)        14168

 max_pooling2d_13 (MaxPooli  (None, 5, 5, 56)          0
 ng2D)

 dropout_13 (Dropout)        (None, 5, 5, 56)          0

 batch_normalization_25 (Ba  (None, 5, 5, 56)          224
 tchNormalization)

 conv2d_20 (Conv2D)          (None, 3, 3, 56)          28280

 batch_normalization_26 (Ba  (None, 3, 3, 56)          224
 tchNormalization)

 flatten_6 (Flatten)         (None, 504)               0

 dense_12 (Dense)            (None, 56)                28280

 batch_normalization_27 (Ba  (None, 56)                224
 tchNormalization)

 dense_13 (Dense)            (None, 10)                570

=================================================================
Total params: 72362 (282.66 KB)
Trainable params: 71970 (281.13 KB)
Non-trainable params: 392 (1.53 KB)
_________________________________________________________________
Epoch 1/50
1750/1750 [==============================] - 12s 6ms/step - loss: 1.0392 - accuracy: 0.6418 - val_loss: 0.6944 - val_accuracy: 0.7446
Epoch 2/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.7470 - accuracy: 0.7343 - val_loss: 0.6153 - val_accuracy: 0.7714
Epoch 3/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6809 - accuracy: 0.7564 - val_loss: 0.5679 - val_accuracy: 0.7906
Epoch 4/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6401 - accuracy: 0.7689 - val_loss: 0.5410 - val_accuracy: 0.8029
Epoch 5/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.6142 - accuracy: 0.7782 - val_loss: 0.5203 - val_accuracy: 0.8123
Epoch 6/50
1750/1750 [==============================] - 10s 5ms/step - loss: 0.5896 - accuracy: 0.7869 - val_loss: 0.5030 - val_accuracy: 0.8207
Epoch 7/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5728 - accuracy: 0.7934 - val_loss: 0.4934 - val_accuracy: 0.8217
Epoch 8/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5573 - accuracy: 0.7981 - val_loss: 0.4802 - val_accuracy: 0.8290
Epoch 9/50
1750/1750 [==============================] - 10s 5ms/step - loss: 0.5453 - accuracy: 0.8021 - val_loss: 0.4702 - val_accuracy: 0.8310
Epoch 10/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5353 - accuracy: 0.8052 - val_loss: 0.4612 - val_accuracy: 0.8341
Epoch 11/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5231 - accuracy: 0.8120 - val_loss: 0.4531 - val_accuracy: 0.8383
Epoch 12/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.5153 - accuracy: 0.8146 - val_loss: 0.4460 - val_accuracy: 0.8417
Epoch 13/50
1750/1750 [==============================] - 9s 5ms/step - loss: 0.5075 - accuracy: 0.8165 - val_loss: 0.4387 - val_accuracy: 0.8431
Epoch 14/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4951 - accuracy: 0.8222 - val_loss: 0.4340 - val_accuracy: 0.8449
Epoch 15/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4942 - accuracy: 0.8214 - val_loss: 0.4303 - val_accuracy: 0.8463
Epoch 16/50
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4885 - accuracy: 0.8234 - val_loss: 0.4255 - val_accuracy: 0.8473
Epoch 17/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4840 - accuracy: 0.8247 - val_loss: 0.4193 - val_accuracy: 0.8487
Epoch 18/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4754 - accuracy: 0.8286 - val_loss: 0.4149 - val_accuracy: 0.8487
Epoch 19/50
1750/1750 [==============================] - 11s 6ms/step - loss: 0.4729 - accuracy: 0.8292 - val_loss: 0.4125 - val_accuracy: 0.8514
Epoch 20/50
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4691 - accuracy: 0.8319 - val_loss: 0.4059 - val_accuracy: 0.8521
Epoch 21/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4641 - accuracy: 0.8338 - val_loss: 0.4058 - val_accuracy: 0.8524
Epoch 22/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4574 - accuracy: 0.8356 - val_loss: 0.4012 - val_accuracy: 0.8544
Epoch 23/50
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4553 - accuracy: 0.8363 - val_loss: 0.3982 - val_accuracy: 0.8557
Epoch 24/50
1750/1750 [==============================] - 11s 7ms/step - loss: 0.4479 - accuracy: 0.8393 - val_loss: 0.3964 - val_accuracy: 0.8566
Epoch 25/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4455 - accuracy: 0.8420 - val_loss: 0.3943 - val_accuracy: 0.8561
Epoch 26/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4432 - accuracy: 0.8419 - val_loss: 0.3896 - val_accuracy: 0.8580
Epoch 27/50
1750/1750 [==============================] - 9s 5ms/step - loss: 0.4390 - accuracy: 0.8423 - val_loss: 0.3867 - val_accuracy: 0.8593
Epoch 28/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4381 - accuracy: 0.8424 - val_loss: 0.3864 - val_accuracy: 0.8593
Epoch 29/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4364 - accuracy: 0.8433 - val_loss: 0.3837 - val_accuracy: 0.8616
Epoch 30/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4312 - accuracy: 0.8458 - val_loss: 0.3808 - val_accuracy: 0.8610
Epoch 31/50
1750/1750 [==============================] - 10s 5ms/step - loss: 0.4312 - accuracy: 0.8444 - val_loss: 0.3780 - val_accuracy: 0.8644
Epoch 32/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4277 - accuracy: 0.8472 - val_loss: 0.3774 - val_accuracy: 0.8633
Epoch 33/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4237 - accuracy: 0.8489 - val_loss: 0.3746 - val_accuracy: 0.8646
Epoch 34/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4216 - accuracy: 0.8476 - val_loss: 0.3745 - val_accuracy: 0.8651
Epoch 35/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4199 - accuracy: 0.8488 - val_loss: 0.3737 - val_accuracy: 0.8644
Epoch 36/50
1750/1750 [==============================] - 11s 6ms/step - loss: 0.4182 - accuracy: 0.8508 - val_loss: 0.3705 - val_accuracy: 0.8666
Epoch 37/50
1750/1750 [==============================] - 10s 6ms/step - loss: 0.4142 - accuracy: 0.8518 - val_loss: 0.3679 - val_accuracy: 0.8677
Epoch 38/50

In [ ]:
params.to_csv(prefix_dir("params.csv"), index=False)
params

In [ ]:
print(f"Min loss from baseline: {min_loss:.2f}%, Max accuracy from baseline: {max_accuracy:.2f}%")

###Kiekvieno modelio klaidų ir tikslumo grafikas parametrų atžvilgiu.

In [ ]:
# https://matplotlib.org/stable/gallery/lines_bars_and_markers/barchart.html#sphx-glr-gallery-lines-bars-and-markers-barchart-py

def plot_multi_bars(
    x_labels, y_bar_name_to_data, x_title):
  # data in order to labels

  x = np.arange(len(x_labels))  # the label locations
  width = 0.25  # the width of the bars
  multiplier = 0

  fig, ax = plt.subplots(layout='constrained')

  for attribute, measurements in y_bar_name_to_data.items():
    offset = width * multiplier
    rects = ax.bar(x + offset, measurements, width, label=attribute)
    ax.bar_label(rects, padding=10)
    multiplier += 1

  # Add some text for labels, title and custom x-axis tick labels, etc.
  ax.set_ylabel('Percentage')
  ax.set_xlabel(x_title)
  ax.set_title(f'Loss and accuracy with respect to changed {x_title}')
  ax.set_xticks(x + width, x_labels)
  ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.15), ncols=2)
  ax.set_ylim(0, 50)
  create_dir(prefix_dir("acc_loss"))
  plt.savefig(prefix_dir(f'acc_loss/{x_title}.png'))

In [ ]:
# generate just random 2 dataframes inline
def generate_random_dataframe():
  return pd.DataFrame(np.random.randint(1, 100, size=(10, 4)), columns=['A', 'B', 'C', 'D'])

generate_random_dataframe().iloc[3:5][0:3].values.tolist()

In [ ]:
def plot_all_param_results(available_params, params):
  i = 0
  # last rows are not counted as they are accuracy and loss
  last_param_index = len(params) - 1
  for column, values in available_params.items():
    next_i = i + len(values) - 1
    # append last param (base) for comparison
    plot_multi_bars(
      x_labels=params[column][i:next_i].tolist() + [params[column][last_param_index]],
      y_bar_name_to_data={
          PARAMS_LOSS_NAME: params['Loss'][i:next_i].tolist() + [params['Loss'][last_param_index]],
          PARAMS_ACC_NAME: params['Accuracy'][i:next_i].tolist() + [params['Accuracy'][last_param_index]]
      },
      x_title=column
    )
    i = next_i

plot_all_param_results(available_params, params)

###Geriausio modelio 30 spėjimų

In [ ]:
best_predictions = best_predictions.argmax(axis=1)
prediction_results = {"Actual index": [], "Predicted": [], "Actual": []}
for i_class in classes["Index"]:
  class_actual_indices = np.where(y_full_test == i_class)[0][0:3]
  prediction_results["Actual index"].extend(class_actual_indices)
  prediction_results["Predicted"].extend(best_predictions[class_actual_indices])
  prediction_results["Actual"].extend([i_class] * 3)
prediction_results = pd.DataFrame(prediction_results)
prediction_results

In [ ]:
prediction_results.to_latex(prefix_dir("results.tex"), index=False)

In [ ]:
# plt.plot(history.history['accuracy'], label='accuracy')
# plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
# plt.xlabel('Epoch')
# plt.ylabel('Accuracy')
# plt.ylim([0.5, 1])
# plt.legend(loc='lower right')

###Geriausio modelio *confusion* matrica

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html
confusion_matrix_obj = confusion_matrix(y_full_test, best_predictions, labels=classes["Index"])
confusion_matrix_display = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix_obj, display_labels=classes["Index"])
# important for plt.savefig before plt.show
confusion_matrix_display.plot().figure_.savefig(prefix_dir("confusion_matrix.png"))
# confusion_matrix_display.plot()